# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 438e2f713769c62dfce4994e03cc2ba835460deed7ee8a2f2b7390697de80eff6a2919d44b198a9078363c04baf74f7ea3e602bbb811d603d7bdae1491a6c8a5

test:
  secret_key_base: e3ffa6d66d8c74a905e4db344420a5840a5ac516318d59fd729452a96a96bcfa08bdf662c0d10e5fca6c46ab4cfcb1133151d0abb10230eccfe3a0b256a20932

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
